"import React from 'react';",
"import Authenticate from './Authenticate/Authenticate.jsx';",
"class View extends React.Component {",
"constructor(props) {",
"super(props);",
"this.state = {",
"show: 'Authenticate",
"};",
"}",
"render() {",
"console.log(`Render View`, this.props);",
"switch (this.state.show) {",
"case 'App':",
"return <App / > ;",
"break;",
"",
"default:",
"return <Authenticate / > ;",
"break;",
"}",
"}",
"}",
"export default View;"